### PR TITLE
Polygon Selection

### PR DESCRIPTION
**Pull request by simonbethke**
I just added a little Polygon selection tool to the toolbar.

https://github.com/user-attachments/assets/4f6c39bd-540f-4467-826e-b4224f8eed60

### CODE REVIEW

**Comment by simonbethke** [comment]
Important things to test for QA are:
* Close with double click and by clicking the start
* When finishing the selection by clicking the start again the dashed line gets brighter
* Change tool with unfinished polygon and get back to this tool (the line should start from the beginning)
* Changing the view is locked as long as I am editing a polygon but works with the tool selected as long as no poly is made
* Regression: Adding (+Ctrl) and Removing (+Shift) the selection from other selections should work too
* The tool can be accessed with shortcut key "O". (I wish I could have used "P", but thats already the word "Picker" that is used as synonym for "Rectangle".... I don't know why)

**Comment by simonbethke** [comment]
Question:
* If when closing, the last point is not used as selection-point, should the dashed line also snap to that start point during edit?

**Review by slimbuck — APPROVED** [review]
Amazing. I just tested this and it works great! Thanks so much!

A few notes:
- The double-click to close is a great addition. Wondering how we can let users know about it.
- 4px to close felt to me a little small. I'd make it bigger... maybe 8px?
- I'd quite like backspace to delete the previously placed point (I can can do this later).
- The mask canvas element should be shared with brush tool (I will do this later).

Thanks again!

**Review by willeastcott — APPROVED** [review]
I think this wins 'PR of the week' competition. 🎉

**Comment by willeastcott** [comment]
I note this partially addresses #76. That issue states that polygon selection is actually more important than lasso selection. But we should probably leave it open assuming we also intend to add a lasso select.

**Pull request merged**
