### PR TITLE
Localize SuperSplat to Chinese, Japanese and Korean

### PR DESCRIPTION
**Pull request by willeastcott**
Use [i18next](https://www.i18next.com/) to localize SuperSplat. Initially, Chinese, Japanese and Korean have been added as the first non-English languages:

Chinese:

image

Japanese:

image

Korean:

image

Note: the localization should autoselect based on the browser's locale. However, you can force it with the `lng` query parameter (i.e. `http://playcanvas.com/supersplat/editor?lng=kr`).

We could potentially externalize the strings in future, but for now, it's quite convenient to have them in the code.

### CODE REVIEW

**Comment by willeastcott** [comment]
If any Japanese speakers can check the translations, I would really appreciate it! I used Copilot to generate them.

**Review by slimbuck — APPROVED** [review]
Fantastichi!

**Comment by yushimatenjin** [comment]
Hello! I've submitted a Pull Request to review and fix the Japanese translation.
https://github.com/playcanvas/supersplat/pull/193

**Comment by willeastcott** [comment]
Thanks, @yushimatenjin - this is now deployed. Can you please go here and verify that the UI is automatically set to Japanese for you?
https://playcanvas.com/supersplat/editor

**Comment by yushimatenjin** [comment]
@willeastcott 
I accessed it and it seems to be working fine!

deploy-01

**Comment by willeastcott** [comment]
That's excellent. Thanks for confirming!

**Comment by willeastcott** [comment]
Hey @nmgyaoyuan, are the Chinese translations OK?

**Pull request merged**
