### PR TITLE
Control Camera Speed

### PR DESCRIPTION
**Pull request by simonbethke**
I added a simple slider that allows to control the camera speed. Currently it is by default set to 5m/s and it can be set between 0.1 and 30 m/s.

However, I found a bug that happens when moving forward through the scene origin. By doing that, the camera turns around and looks back to the origin. Up and Down arrows now switched directions. https://github.com/playcanvas/supersplat/issues/286

### CODE REVIEW

**Review by slimbuck — COMMENTED** [review]
This is great, thanks so much! Left a few comments - please call the variable camera flySpeed.

**Comment by simonbethke** [comment]
I have made those changes. However, I wish I could make the slider-control transparent for key-up/down events. Any idea how to accomplish that?

**Comment by slimbuck** [comment]
Might be possible, but quite fiddly.

How about hooking + and - keys to speed camera up and down?

**Comment by slimbuck** [comment]
I've merged the changes from yesterday's lint update into your branch.

**Comment by slimbuck** [comment]
I also added the missing localisations.

Please check you're happy before I merge.

**Review by slimbuck — APPROVED** [review]

**Comment by simonbethke** [comment]
I think you changed every single line of code :) 
All good

**Pull request merged**
