### PR TITLE
Specify colors by url parameter

### PR DESCRIPTION
**Pull request by slimbuck**
Fixes: #329

This PR:
- adds ability to overwrite `selectedClr`, `unselectedClr` and `lockedClr` the way `bgClr` can
- colors are specified as an array, for example `&selectedClr=0.8,0,0,0.5`
- also deleted some legacy classes from config and code

### CODE REVIEW

**Comment by willeastcott** [comment]
Camel-case in URL params bothers me for some reason. But you're presumably doing this because they match up with JS property names?

**Comment by slimbuck** [comment]
Yep

**Review by willeastcott — APPROVED** [review]

**Comment by willeastcott** [comment]
I mean, don't want to be annoying here, but I'd almost prefer a `Map` of nice URL params to internal property names.

**Comment by slimbuck** [comment]
We could do, but:
- this feature shouldn't be needed in the near future when we introduce document format
- if we have a map we'd  have to document it somewhere. currently there is just one reference and everything shares it

**Comment by willeastcott** [comment]
OK, I shall bow to your supreme authority on this occasion.

**Comment by slimbuck** [comment]
Which format would you prefer for url params, kebab-case? I might be able to do an auto-case-conversion...

**Comment by willeastcott** [comment]
Yeah, I ❤️ kebabs. 😋

**Comment by slimbuck** [comment]
I've added support for all values to specify either case, `bg-clr` or `bgClr` 👍🏻

**Pull request merged**
