### PR TITLE
Import-export

### PR DESCRIPTION
**Pull request by simonbethke**
- Change the main Scene menu-terminology from Open/Save to Import/Export
- Renamed the keyword for .splat-files to "ssplat"
- Added import-functionality for .splat files

### CODE REVIEW

**Comment by slimbuck** [comment]
This is looking great @simonbethke thanks so much!

Can I ask you to split the two changes into different PR's though? (i.e. adding `.splat` load support and changing the menu layout).

The menu layout / ui changes will be discussed internally with design team and I wouldn't want that to impede getting the `.splat` support merged.

**Comment by simonbethke** [comment]
Yea, I realized that merging both was no good idea. I will try to get this done

**Comment by simonbethke** [comment]
Seems as if I broke it with rebasing :(

**Comment by simonbethke** [comment]
This is being added in https://github.com/playcanvas/supersplat/pull/218

**Pull request closed without merging**
